.TH "/Users/Alex/github/AWEMediaCenter/Code/libs Directory Reference" 3 "Fri Apr 18 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Alex/github/AWEMediaCenter/Code/libs Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBgeneric_file_reader\fP"
.br
.ti -1c
.RI "directory \fBinternet_reader\fP"
.br
.ti -1c
.RI "directory \fBjson\fP"
.br
.in -1c
