.TH "/Users/Alex/github/AWEMediaCenter/Code/ui/widgets Directory Reference" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Alex/github/AWEMediaCenter/Code/ui/widgets Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcollection\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBImageItemWidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBImageItemWidget\&.h\fP"
.br
.ti -1c
.RI "file \fBItemWidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBItemWidget\&.h\fP"
.br
.ti -1c
.RI "file \fBMediaItemWidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMediaItemWidget\&.h\fP"
.br
.ti -1c
.RI "file \fBTextItemWidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTextItemWidget\&.h\fP"
.br
.ti -1c
.RI "file \fBTransparentScrollArea\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTransparentScrollArea\&.h\fP"
.br
.in -1c
