.TH "/Users/Alex/github/AWEMediaCenter/Code/scraper Directory Reference" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Alex/github/AWEMediaCenter/Code/scraper Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAWEJSONScraper\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAWEJSONScraper\&.h\fP"
.br
.ti -1c
.RI "file \fBAWEMetadataScraper\&.h\fP"
.br
.in -1c
