.TH "/Users/Alex/github/AWEMediaCenter/Code Directory Reference" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Alex/github/AWEMediaCenter/Code Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdebug_macros\fP"
.br
.ti -1c
.RI "directory \fBitems\fP"
.br
.ti -1c
.RI "directory \fBlibs\fP"
.br
.ti -1c
.RI "directory \fBplayer\fP"
.br
.ti -1c
.RI "directory \fBscraper\fP"
.br
.ti -1c
.RI "directory \fBsettings\fP"
.br
.ti -1c
.RI "directory \fBtype\fP"
.br
.ti -1c
.RI "directory \fBui\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmoc_AWEMediaItem\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmoc_FolderBrowser\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmoc_FolderPane\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmoc_ImageItemWidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmoc_ImagePane\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmoc_InfoPane\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmoc_ItemCollectionWidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmoc_ItemGridWidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmoc_ItemListWidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmoc_ItemWidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmoc_MediaItemWidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmoc_TextItemWidget\&.cpp\fP"
.br
.in -1c
