.TH "/Users/Alex/github/AWEMediaCenter/Code Directory Reference" 3 "Fri Apr 18 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Alex/github/AWEMediaCenter/Code Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdebug_macros\fP"
.br
.ti -1c
.RI "directory \fBitems\fP"
.br
.ti -1c
.RI "directory \fBlibs\fP"
.br
.ti -1c
.RI "directory \fBplayer\fP"
.br
.ti -1c
.RI "directory \fBscraper\fP"
.br
.ti -1c
.RI "directory \fBsettings\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.in -1c
