.TH "/Users/Alex/github/AWEMediaCenter/Code/ui/pane Directory Reference" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Alex/github/AWEMediaCenter/Code/ui/pane Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFolderPane\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFolderPane\&.h\fP"
.br
.ti -1c
.RI "file \fBImagePane\&.cpp\fP"
.br
.ti -1c
.RI "file \fBImagePane\&.h\fP"
.br
.ti -1c
.RI "file \fBInfoPane\&.cpp\fP"
.br
.ti -1c
.RI "file \fBInfoPane\&.h\fP"
.br
.ti -1c
.RI "file \fBPane\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPane\&.h\fP"
.br
.ti -1c
.RI "file \fBTextPane\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTextPane\&.h\fP"
.br
.in -1c
