.TH "AWE" 3 "Fri Apr 18 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AWE \- 
.PP
Backend for AWEMC\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFolder\fP"
.br
.RI "\fIA folder that contains \fC\fBMediaItem\fP\fPs\&. \fP"
.ti -1c
.RI "class \fBJSONService\fP"
.br
.RI "\fIAn external media service (aka application) described by a JSON file\&. \fP"
.ti -1c
.RI "class \fBMediaFile\fP"
.br
.RI "\fIRepresents a media file\&. \fP"
.ti -1c
.RI "class \fBMediaItem\fP"
.br
.RI "\fIRepresents a media file, folder, or service\&. \fP"
.ti -1c
.RI "class \fBMediaService\fP"
.br
.RI "\fIA media service, which is basically an application with its own media browser\&. \fP"
.ti -1c
.RI "class \fBJSONPlayer\fP"
.br
.RI "\fIRepresents an external media player designed in a JSON file\&. \fP"
.ti -1c
.RI "class \fBMediaPlayer\fP"
.br
.RI "\fIRepresents an abstract media player's functions\&. \fP"
.ti -1c
.RI "class \fBJSONScraper\fP"
.br
.RI "\fIA metadata scraper based on JSON files\&. \fP"
.ti -1c
.RI "class \fBMetadataScraper\fP"
.br
.RI "\fIDefines the general interface for a metadata scraper\&. \fP"
.ti -1c
.RI "class \fBGlobalSettings\fP"
.br
.RI "\fIHolds the global settings for AWEMC\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::smatch \fBBackrefList\fP"
.br
.RI "\fIDefines a list of sub expressions\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Backend for AWEMC\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for AWE Media Center from the source code\&.
