.TH "AWE::JSONPlayer" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AWE::JSONPlayer \- 
.PP
Represents an external media player designed in a JSON file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AWEJSONPlayer\&.h>\fP
.PP
Inherits \fBAWE::MediaPlayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJSONPlayer\fP (\fBJson::Value\fP &player)"
.br
.RI "\fIConstruct a media player from the given JSON object\&. \fP"
.ti -1c
.RI "virtual int \fBplay\fP (\fBMediaFile\fP *file)"
.br
.RI "\fIPlay the given file\&. \fP"
.ti -1c
.RI "virtual QString \fBgetName\fP () const "
.br
.RI "\fIGet the name of the player\&. \fP"
.ti -1c
.RI "virtual bool \fBcanPlay\fP (\fBMediaFile\fP *file)"
.br
.RI "\fIDetermine if the given media file can be played by this player\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QString \fBmyName\fP"
.br
.RI "\fIThe name of the player\&. \fP"
.ti -1c
.RI "QString \fBmyProgram\fP"
.br
.RI "\fIThe program to be run\&. \fP"
.ti -1c
.RI "QString \fBmyArguments\fP"
.br
.RI "\fIThe arguments to be passed\&. \fP"
.ti -1c
.RI "QStringList \fBmyFileTypes\fP"
.br
.RI "\fIThe possible file types that can be played\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Represents an external media player designed in a JSON file\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JSONPlayer::JSONPlayer (\fBJson::Value\fP &player)"

.PP
Construct a media player from the given JSON object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIplayer\fP The JSON object representing this player\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool JSONPlayer::canPlay (\fBMediaFile\fP *file)\fC [virtual]\fP"

.PP
Determine if the given media file can be played by this player\&. For JSON based players, this is determined using the file extension and the \fC'filetypes'\fP tag\&.
.PP
\fBParameters:\fP
.RS 4
\fIfile\fP The file to determine playability for\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fCtrue\fP if this player can play \fCfile\fP, \fCfalse\fP otherwise\&. 
.RE
.PP

.PP
Implements \fBAWE::MediaPlayer\fP\&.
.SS "QString JSONPlayer::getName () const\fC [virtual]\fP"

.PP
Get the name of the player\&. 
.PP
\fBReturns:\fP
.RS 4
The name of the player\&. 
.RE
.PP

.PP
Implements \fBAWE::MediaPlayer\fP\&.
.SS "int JSONPlayer::play (\fBMediaFile\fP *file)\fC [virtual]\fP"

.PP
Play the given file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfile\fP The media file to play\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fCtrue\fP if \fCfile\fP played successfully, \fCfalse\fP otherwise\&. 
.RE
.PP

.PP
Implements \fBAWE::MediaPlayer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AWE Media Center from the source code\&.
