.TH "AWEFolder" 3 "Thu Apr 17 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AWEFolder \- 
.PP
A folder that contains \fC\fBAWEMediaItem\fP\fPs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AWEFolder\&.h>\fP
.PP
Inherits \fBAWEMediaItem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAWEFolder\fP (const QDir &folder, \fBAWEGlobalSettings\fP *settings)"
.br
.RI "\fIConstruct from the folder's settings and from the global settings\&. \fP"
.ti -1c
.RI "virtual \fB~AWEFolder\fP ()"
.br
.RI "\fIDeconstructor\&. \fP"
.ti -1c
.RI "virtual ItemType \fBgetItemType\fP () const "
.br
.RI "\fIDetermine the basic type (folder, file, service) \fP"
.ti -1c
.RI "virtual std::vector
.br
< \fBAWEMediaItem\fP * > & \fBgetItems\fP ()"
.br
.RI "\fIGet a list of all of the items this folder contains\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A folder that contains \fC\fBAWEMediaItem\fP\fPs\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AWEFolder::AWEFolder (const QDir &folder, \fBAWEGlobalSettings\fP *settings)"

.PP
Construct from the folder's settings and from the global settings\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfolder\fP The configuration file for this folder\&. 
.br
\fIsettings\fP The global settings\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::vector< \fBAWEMediaItem\fP * > & AWEFolder::getItems ()\fC [virtual]\fP"

.PP
Get a list of all of the items this folder contains\&. 
.PP
\fBReturns:\fP
.RS 4
All of the items this folder contains\&. 
.RE
.PP

.SS "ItemType AWEFolder::getItemType () const\fC [virtual]\fP"

.PP
Determine the basic type (folder, file, service) 
.PP
\fBReturns:\fP
.RS 4
The basic type of this item\&. 
.RE
.PP

.PP
Implements \fBAWEMediaItem\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AWE Media Center from the source code\&.
