.TH "Json::BatchAllocator< AllocatedType, objectPerAllocation >" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::BatchAllocator< AllocatedType, objectPerAllocation > \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBatchInfo\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef AllocatedType \fBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBatchAllocator\fP (unsigned int objectsPerPage=255)"
.br
.ti -1c
.RI "AllocatedType * \fBallocate\fP ()"
.br
.ti -1c
.RI "void \fBrelease\fP (AllocatedType *object)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBBatchAllocator\fP (const \fBBatchAllocator\fP &)"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBBatchAllocator\fP &)"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static \fBBatchInfo\fP * \fBallocateBatch\fP (unsigned int objectsPerPage)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBBatchInfo\fP * \fBbatches_\fP"
.br
.ti -1c
.RI "\fBBatchInfo\fP * \fBcurrentBatch_\fP"
.br
.ti -1c
.RI "AllocatedType * \fBfreeHead_\fP"
.br
.RI "\fIHead of a single linked list within the allocated space of freeed object\&. \fP"
.ti -1c
.RI "unsigned int \fBobjectsPerPage_\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename AllocatedType , const unsigned int objectPerAllocation> AllocatedType* \fBJson::BatchAllocator\fP< AllocatedType, objectPerAllocation >::allocate ()\fC [inline]\fP"
allocate space for an array of objectPerAllocation object\&. 
.PP
\fBWarning:\fP
.RS 4
it is the responsability of the caller to call objects constructors\&. 
.RE
.PP

.SS "template<typename AllocatedType , const unsigned int objectPerAllocation> void \fBJson::BatchAllocator\fP< AllocatedType, objectPerAllocation >::release (AllocatedType *object)\fC [inline]\fP"
Release the object\&. 
.PP
\fBWarning:\fP
.RS 4
it is the responsability of the caller to actually destruct the object\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AWE Media Center from the source code\&.
