.TH "Json::Value::CommentInfo" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::Value::CommentInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetComment\fP (const char *text)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBcomment_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AWE Media Center from the source code\&.
