.TH "Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::BatchAllocator< AllocatedType, objectPerAllocation >::BatchInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBatchInfo\fP * \fBnext_\fP"
.br
.ti -1c
.RI "AllocatedType * \fBused_\fP"
.br
.ti -1c
.RI "AllocatedType * \fBend_\fP"
.br
.ti -1c
.RI "AllocatedType \fBbuffer_\fP [objectPerAllocation]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AWE Media Center from the source code\&.
