.TH "Json::Reader::ErrorInfo" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::Reader::ErrorInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBToken\fP \fBtoken_\fP"
.br
.ti -1c
.RI "std::string \fBmessage_\fP"
.br
.ti -1c
.RI "Location \fBextra_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AWE Media Center from the source code\&.
