.TH "md___users__alex_github__a_w_e_media_center__code_player__r_e_a_d_m_e" 3 "Fri Apr 18 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md___users__alex_github__a_w_e_media_center__code_player__r_e_a_d_m_e \- Media Players 
Media players play \&.\&./items/README\&.md 'media files', using either a terminal command or a plugin\&.
.PP
.SH "External JSON Players"
.PP
.PP
The JSON file for a media player looks like this: 
.PP
.nf
{
    "name": "player name",

    "program": "program to run",

    "args": "arguments to pass to the program with file references"
}

.fi
.PP
.PP
The file references to \fC'args'\fP can be: 
.PP
.nf
{1} - the absolute path to the media file

.fi
.PP
.PP
.SH "Internal Plugin Players"
.PP
.PP
Internal media players must implement the \fCMediaPlayer\fP interface and fill out the accompanying JSON file: 
.PP
.nf
{
    "name": "player name",

    "library": "dynamic library file"
} 
.fi
.PP
 
