.TH "md___users__alex_github__a_w_e_media_center__code__r_e_a_d_m_e" 3 "Fri Apr 18 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md___users__alex_github__a_w_e_media_center__code__r_e_a_d_m_e \- Developer Information 
AWEMC is programmed using C++ and relies on \fCQt\fP, \fCcURL\fP, and (eventually) \fCSDL\fP\&. \fCJsonCpp\fP is included in the source code\&.
.PP
There are 7 central concepts you should understand:
.PP
.IP "\(bu" 2
\fBMedia items\fP are organized in a folder structure using JSON files to hold metadata and such\&.
.IP "\(bu" 2
\fBMedia players\fP play media files\&.
.IP "\(bu" 2
\fBMedia services\fP are standalone applications, like a web browser, Netflix, or iTunes\&.
.IP "\(bu" 2
\fBMetadata scrapers\fP get relevant information and images for a media item\&.
.IP "\(bu" 2
\fBMedia types\fP describe the default metadata values for a collection of items, like Movies or TV Shows\&.
.IP "\(bu" 2
\fBFolder generators\fP make a folder structure with organization based on things like Genre for a specific media type\&. They also use metadata scrapers to collect information about media items to be placed in the folder structure\&.
.IP "\(bu" 2
Skins describe the way the UI looks and give default images to files\&.
.PP
.PP
Also, all classes built into AWEMC should be prefixed by 'AWE'\&. 
