.TH "TCOM::Color" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TCOM::Color \- 
.PP
Defines a color to be output to a bash terminal window\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <color\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "char \fBgetColorCode\fP () const "
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBColor\fP \fBBLACK\fP"
.br
.RI "\fIThe color black\&. \fP"
.ti -1c
.RI "static const \fBColor\fP \fBRED\fP"
.br
.RI "\fIThe color red\&. \fP"
.ti -1c
.RI "static const \fBColor\fP \fBGREEN\fP"
.br
.RI "\fIThe color green\&. \fP"
.ti -1c
.RI "static const \fBColor\fP \fBYELLOW\fP"
.br
.RI "\fIThe color yellow\&. \fP"
.ti -1c
.RI "static const \fBColor\fP \fBBLUE\fP"
.br
.RI "\fIThe color blue\&. \fP"
.ti -1c
.RI "static const \fBColor\fP \fBMAGENTA\fP"
.br
.RI "\fIThe color magenta (purple, basically)\&. \fP"
.ti -1c
.RI "static const \fBColor\fP \fBCYAN\fP"
.br
.RI "\fIThe color cyan (a lighter blue)\&. \fP"
.ti -1c
.RI "static const \fBColor\fP \fBWHITE\fP"
.br
.RI "\fIThe color white\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBColor\fP (char c)"
.br
.RI "\fIConstruct a color from its number code\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "char \fBmyCode\fP"
.br
.RI "\fIThe number determining the code\&. \fP"
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBColor\fP &c)"
.br
.RI "\fIMake the terminal output this color as the foreground\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Defines a color to be output to a bash terminal window\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Color::Color (charc)\fC [private]\fP"

.PP
Construct a color from its number code\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP The number code for this color\&. 
.RE
.PP

.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream &os, const \fBColor\fP &c)\fC [friend]\fP"

.PP
Make the terminal output this color as the foreground\&. 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP The output stream to write to\&. 
.br
\fIc\fP The color to change to\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The parameter \fCos\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AWE Media Center from the source code\&.
