.TH "todo" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBClass \fBAWE::GlobalSettings\fP \fP" 1c
Skins 
.PP
\fBUI\fP delegate (with user prompting) 
.IP "\fBClass \fBAWE::JSONScraper\fP \fP" 1c
Change \fCmyType\fP to be the mystical know-all configuration object\&. 
.IP "\fBMember \fBAWE::JSONScraper::checkProcedureValidity\fP (\fBJson::Value\fP &procedure, int capCount)\fP" 1c
This entire function (which at the moment just returns \fCtrue\fP) 
.IP "\fBMember \fBAWE::JSONScraper::checkValidity\fP ()\fP" 1c
This entire function (which at the moment just returns \fCtrue\fP) 
.IP "\fBMember \fBAWE::JSONScraper::scrapeDataForFile\fP (MediaItem *file, bool askUser, bool import, bool inheritMetadata)\fP" 1c
boolean flags 
.IP "\fBMember \fBAWE::JSONScraper::scrapeDataForFile\fP (Folder *placeInMe, GlobalSettings *globalSettings, QDir file, bool askUser, bool import, bool inheritMetadata)\fP" 1c
boolean flags 
.IP "\fBClass \fBAWE::MediaPlayer\fP \fP" 1c
Make plugin interface\&.  
.IP "\fBMember \fBAWE::MetadataScraper::scrapeDataForFile\fP (Folder *placeInMe, GlobalSettings *globalSettings, QDir file, bool askUser, bool import, bool inheritMetadata)=0\fP" 1c
boolean flags 
.IP "\fBNamespace \fBUI\fP \fP" 1c
Create the \fBUI\fP delegate class\&.  
.IP "\fBClass \fBUI::FolderPane\fP \fP" 1c
Other layout options, possibly with icons\&. 
.PP

