.TH "todo" 3 "Fri Apr 18 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBClass \fBAWE::GlobalSettings\fP \fP" 1c
Skins\&.\&.\&. 
.PP
Get a better folder adding system\&. 
.IP "\fBClass \fBAWE::JSONScraper\fP \fP" 1c
Change \fCmyType\fP to be the mystical know-all configuration object\&. 
.IP "\fBMember \fBAWE::JSONScraper::scrapeDataForFile\fP (MediaFile *file, bool askUser, bool import)\fP" 1c
\fCimport\fP and \fCaskUser\fP 
.IP "\fBClass \fBAWE::MediaPlayer\fP \fP" 1c
Make plugin interface\&. 
.PP

