.TH "UI" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI \- 
.PP
Contains the user interface classes of AWEMC\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFolderBrowser\fP"
.br
.RI "\fIA window contents pane designed for browsing files\&. \fP"
.ti -1c
.RI "class \fBWindowContents\fP"
.br
.RI "\fIAn interface that describes what could be the contents of the main window\&. \fP"
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "\fIThe main window of AWEMC, which allows the user to browse through the application\&. \fP"
.ti -1c
.RI "class \fBFolderPane\fP"
.br
.RI "\fIAllows the user to browse through the items of a folder\&. \fP"
.ti -1c
.RI "class \fBImagePane\fP"
.br
.RI "\fIDefines a class that holds icons and fanart images\&. \fP"
.ti -1c
.RI "class \fBInfoPane\fP"
.br
.RI "\fIDisplays the details and description of a media item\&. \fP"
.ti -1c
.RI "class \fBPane\fP"
.br
.RI "\fIA surface representing a pane of widgets\&. \fP"
.ti -1c
.RI "class \fBTextPane\fP"
.br
.RI "\fIThis class acts as a replacement for \fCQLabel\fP when text is needed in a particular font\&. \fP"
.ti -1c
.RI "class \fBItemCollectionWidget\fP"
.br
.RI "\fIAn abstract, scrollable collection of item widgets\&. \fP"
.ti -1c
.RI "class \fBItemGridWidget\fP"
.br
.RI "\fIAn item collection based on a grid layout\&. \fP"
.ti -1c
.RI "class \fBItemListWidget\fP"
.br
.RI "\fIAn item collection based off of lists\&. \fP"
.ti -1c
.RI "class \fBImageItemWidget\fP"
.br
.RI "\fIA \fCQListWidgetItem\fP that holds an image\&. \fP"
.ti -1c
.RI "class \fBItemWidget\fP"
.br
.RI "\fIDefines an abstract item widget for lists\&. \fP"
.ti -1c
.RI "class \fBMediaItemWidget\fP"
.br
.RI "\fIA list widget class that holds a media item\&. \fP"
.ti -1c
.RI "class \fBTextItemWidget\fP"
.br
.RI "\fIDisplays text in a specific font\&. \fP"
.ti -1c
.RI "class \fBTransparentScrollArea\fP"
.br
.RI "\fIEssentially \fCQScrollArea\fP, but with a transparent background\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains the user interface classes of AWEMC\&. 


.PP
\fBTodo\fP
.RS 4
Create the \fBUI\fP delegate class\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for AWE Media Center from the source code\&.
