.TH "UI::FolderPane" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI::FolderPane \- 
.PP
Allows the user to browse through the items of a folder\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FolderPane\&.h>\fP
.PP
Inherits \fBUI::Pane\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual void \fBsetFolder\fP (\fBAWE::Folder\fP *folder)"
.br
.RI "\fIChange the folder to the given folder\&. \fP"
.ti -1c
.RI "virtual void \fBrefresh\fP ()"
.br
.RI "\fIRefresh the item lists\&. \fP"
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBitemHighlighted\fP (\fBAWE::MediaItem\fP *item)"
.br
.RI "\fISent when an item is highlighted, but not selected\&. \fP"
.ti -1c
.RI "void \fBitemSelected\fP (\fBAWE::MediaItem\fP *item)"
.br
.RI "\fISent when the user has opened an item\&. \fP"
.ti -1c
.RI "void \fBgoUpOne\fP ()"
.br
.RI "\fISent when the user wants to go back one folder\&. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFolderPane\fP (QWidget *parent)"
.br
.RI "\fIConstruct with the given parent widget\&. \fP"
.ti -1c
.RI "virtual \fB~FolderPane\fP ()"
.br
.RI "\fIDestroys this object\&. \fP"
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBrespondToItemHighlight\fP (\fBItemWidget\fP *curr)"
.br
.RI "\fIInternal slot for emitting item highlighting\&. \fP"
.ti -1c
.RI "void \fBrespondToItemSelected\fP (\fBItemWidget\fP *item)"
.br
.RI "\fIInternal slot for emitting item selection\&. \fP"
.ti -1c
.RI "void \fBrespondToViewModeChoice\fP (int mode)"
.br
.RI "\fIInternal slot for changing the view mode\&. \fP"
.ti -1c
.RI "void \fBrespondToBackButton\fP ()"
.br
.RI "\fIInternal slot for emitting back button events\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBAWE::Folder\fP * \fBmyFolder\fP"
.br
.RI "\fIThe folder whose contents are displayed\&. \fP"
.ti -1c
.RI "QVBoxLayout * \fBmyMainLayout\fP"
.br
.RI "\fIThe main layout for this widget\&. \fP"
.ti -1c
.RI "QPushButton * \fBmyBackButton\fP"
.br
.RI "\fIThe back button\&. \fP"
.ti -1c
.RI "QComboBox * \fBmyViewSelectionMenu\fP"
.br
.RI "\fIView selection menu\&. \fP"
.ti -1c
.RI "QStackedLayout * \fBmyMediaItemLayout\fP"
.br
.RI "\fIThe layout to switch between item view modes\&. \fP"
.ti -1c
.RI "\fBItemListWidget\fP * \fBmyMediaItemList\fP"
.br
.RI "\fIThe list of contained media items\&. \fP"
.ti -1c
.RI "\fBItemGridWidget\fP * \fBmyMediaItemGrid\fP"
.br
.RI "\fIThe grid of contained media items\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Allows the user to browse through the items of a folder\&. 

This is a collection of \fBUI\fP items holding a list of \fC\fBAWE::MediaItem\fP\fPs and a back button\&.
.PP
\fBTodo\fP
.RS 4
Other layout options, possibly with icons\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "FolderPane::FolderPane (QWidget *parent)"

.PP
Construct with the given parent widget\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP The parent widget\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void UI::FolderPane::itemHighlighted (\fBAWE::MediaItem\fP *item)\fC [signal]\fP"

.PP
Sent when an item is highlighted, but not selected\&. 
.PP
\fBParameters:\fP
.RS 4
\fIitem\fP The item that was highlighted\&. 
.RE
.PP

.SS "void UI::FolderPane::itemSelected (\fBAWE::MediaItem\fP *item)\fC [signal]\fP"

.PP
Sent when the user has opened an item\&. 
.PP
\fBParameters:\fP
.RS 4
\fIitem\fP The item that was chosen\&. 
.RE
.PP

.SS "void FolderPane::respondToItemHighlight (\fBItemWidget\fP *curr)\fC [private]\fP, \fC [slot]\fP"

.PP
Internal slot for emitting item highlighting\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcurr\fP The highlighted item\&. 
.RE
.PP

.SS "void FolderPane::respondToItemSelected (\fBItemWidget\fP *item)\fC [private]\fP, \fC [slot]\fP"

.PP
Internal slot for emitting item selection\&. 
.PP
\fBParameters:\fP
.RS 4
\fIitem\fP The chosen item\&. 
.RE
.PP

.SS "void FolderPane::respondToViewModeChoice (intmode)\fC [private]\fP, \fC [slot]\fP"

.PP
Internal slot for changing the view mode\&. 
.PP
\fBParameters:\fP
.RS 4
\fImode\fP The new view mode\&. 
.RE
.PP

.SS "void FolderPane::setFolder (\fBAWE::Folder\fP *folder)\fC [virtual]\fP, \fC [slot]\fP"

.PP
Change the folder to the given folder\&. Changes the list of items that the user can select\&.
.PP
\fBParameters:\fP
.RS 4
\fIfolder\fP The folder to change to\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AWE Media Center from the source code\&.
