.TH "UI::FolderBrowser" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI::FolderBrowser \- 
.PP
A window contents pane designed for browsing files\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FolderBrowser\&.h>\fP
.PP
Inherits QObject, and \fBUI::WindowContents\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual void \fBopenItem\fP (\fBAWE::MediaItem\fP *item)"
.br
.RI "\fIOpen the given item\&. \fP"
.ti -1c
.RI "virtual void \fBmoveUpOneFolder\fP ()"
.br
.RI "\fIGo up one folder\&. \fP"
.ti -1c
.RI "virtual void \fBsetTitleBarText\fP (QString text)"
.br
.RI "\fISet the title bar text\&. \fP"
.ti -1c
.RI "virtual void \fBsetBackgroundImage\fP (QPixmap image)"
.br
.RI "\fISet the background image\&. \fP"
.ti -1c
.RI "virtual void \fBscrapeForMetadata\fP (\fBAWE::MediaItem\fP *item, \fBAWE::MetadataScraper\fP *scraper, bool askUser, bool import, bool inheritMetadata)"
.br
.RI "\fIScrape for metadata\&. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFolderBrowser\fP (\fBAWE::GlobalSettings\fP *settings)"
.br
.RI "\fIConstruct using AWEMC's global settings\&. \fP"
.ti -1c
.RI "virtual \fB~FolderBrowser\fP ()"
.br
.RI "\fIDestroy this object\&. \fP"
.ti -1c
.RI "virtual QString \fBgetType\fP ()"
.br
.RI "\fIGet the type of contents, i\&.e\&. \fC'Folder Browser'\fP\&. \fP"
.ti -1c
.RI "virtual void \fBsetParent\fP (\fBMainWindow\fP *window)"
.br
.RI "\fISet the parent of this contents pane (i\&.e\&., the main window)\&. \fP"
.ti -1c
.RI "virtual QWidget * \fBgetWidget\fP ()"
.br
.RI "\fIGets the main widget for this screen\&. \fP"
.ti -1c
.RI "virtual void \fBopen\fP ()"
.br
.RI "\fIOpens the root folder\&. \fP"
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "virtual void \fBrespondToIconChange\fP (QPixmap image)"
.br
.RI "\fIInternal slot for refreshing the folder list\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBAWE::GlobalSettings\fP * \fBmyGlobalSettings\fP"
.br
.RI "\fIThe global settings of AWEMC\&. \fP"
.ti -1c
.RI "QStack< \fBAWE::Folder\fP * > \fBmyBrowserHistory\fP"
.br
.RI "\fIThe folder browsing history\&. \fP"
.ti -1c
.RI "QWidget * \fBmyMainWidget\fP"
.br
.RI "\fIThe main widget for folder browsing\&. \fP"
.ti -1c
.RI "QStackedLayout * \fBmyMainLayout\fP"
.br
.RI "\fIThe stacked layout with everything on it\&. \fP"
.ti -1c
.RI "\fBImageItemWidget\fP * \fBmyBackgroundImage\fP"
.br
.RI "\fIThe background image\&. \fP"
.ti -1c
.RI "QWidget * \fBmyForegroundWidget\fP"
.br
.RI "\fIThe foreground layouts\&. \fP"
.ti -1c
.RI "QVBoxLayout * \fBmyForegroundMainLayout\fP"
.br
.RI "\fIThe foreground layouts\&. \fP"
.ti -1c
.RI "QHBoxLayout * \fBmyForegroundLayout\fP"
.br
.RI "\fIThe foreground layouts\&. \fP"
.ti -1c
.RI "\fBTextPane\fP * \fBmyTitleBar\fP"
.br
.RI "\fIThe title bar\&. \fP"
.ti -1c
.RI "\fBImagePane\fP * \fBmyImagePane\fP"
.br
.RI "\fIThe item image pane\&. \fP"
.ti -1c
.RI "\fBFolderPane\fP * \fBmyFolderPane\fP"
.br
.RI "\fIThe folder pane\&. \fP"
.ti -1c
.RI "\fBInfoPane\fP * \fBmyInfoPane\fP"
.br
.RI "\fIThe item info pane\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A window contents pane designed for browsing files\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FolderBrowser::FolderBrowser (\fBAWE::GlobalSettings\fP *settings)"

.PP
Construct using AWEMC's global settings\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsettings\fP The global settings of AWEMC\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "QString FolderBrowser::getType ()\fC [virtual]\fP"

.PP
Get the type of contents, i\&.e\&. \fC'Folder Browser'\fP\&. 
.PP
\fBReturns:\fP
.RS 4
\fC'Folder Browser'\fP 
.RE
.PP

.PP
Implements \fBUI::WindowContents\fP\&.
.SS "QWidget * FolderBrowser::getWidget ()\fC [virtual]\fP"

.PP
Gets the main widget for this screen\&. All of the \fBUI\fP elements for folder browsing are inside of this widget\&.
.PP
\fBReturns:\fP
.RS 4
The main folder browsing widget\&. 
.RE
.PP

.PP
Implements \fBUI::WindowContents\fP\&.
.SS "void FolderBrowser::moveUpOneFolder ()\fC [virtual]\fP, \fC [slot]\fP"

.PP
Go up one folder\&. If this is the root folder, this function does nothing\&. 
.SS "void FolderBrowser::openItem (\fBAWE::MediaItem\fP *item)\fC [virtual]\fP, \fC [slot]\fP"

.PP
Open the given item\&. If it is a folder, it is opened in the folder pane\&. If it is a file or service, it is passed onward to the main window so that it can open it\&.
.PP
\fBParameters:\fP
.RS 4
\fIitem\fP The media item to open\&. 
.RE
.PP

.SS "void FolderBrowser::respondToIconChange (QPixmapimage)\fC [private]\fP, \fC [virtual]\fP, \fC [slot]\fP"

.PP
Internal slot for refreshing the folder list\&. 
.PP
\fBParameters:\fP
.RS 4
\fIimage\fP The (ignored) icon image\&. 
.RE
.PP

.SS "void FolderBrowser::scrapeForMetadata (\fBAWE::MediaItem\fP *item, \fBAWE::MetadataScraper\fP *scraper, boolaskUser, boolimport, boolinheritMetadata)\fC [virtual]\fP, \fC [slot]\fP"

.PP
Scrape for metadata\&. 
.PP
\fBParameters:\fP
.RS 4
\fIitem\fP The item to get metadata for\&. 
.br
\fIscraper\fP The scraper to use\&. 
.br
\fIaskUser\fP \fCtrue\fP if the user should be prompted at appropriate times, \fCfalse\fP if no prompting should occur\&. 
.br
\fIimport\fP \fCtrue\fP if metadata files should be imported, \fCfalse\fP if only absolutely necessary\&. 
.br
\fIinheritMetadata\fP \fCtrue\fP if the item should inherit metadata from the containing folder, \fCfalse\fP otherwise\&. 
.RE
.PP

.SS "void FolderBrowser::setBackgroundImage (QPixmapimage)\fC [virtual]\fP, \fC [slot]\fP"

.PP
Set the background image\&. 
.PP
\fBParameters:\fP
.RS 4
\fIimage\fP The new background image\&. 
.RE
.PP

.SS "void FolderBrowser::setParent (\fBMainWindow\fP *window)\fC [virtual]\fP"

.PP
Set the parent of this contents pane (i\&.e\&., the main window)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwindow\fP The \fC\fBMainWindow\fP\fP of AWEMC\&. 
.RE
.PP

.PP
Implements \fBUI::WindowContents\fP\&.
.SS "void FolderBrowser::setTitleBarText (QStringtext)\fC [virtual]\fP, \fC [slot]\fP"

.PP
Set the title bar text\&. 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP The new title bar text\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AWE Media Center from the source code\&.
