.TH "UI::ImagePane" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI::ImagePane \- 
.PP
Defines a class that holds icons and fanart images\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImagePane\&.h>\fP
.PP
Inherits \fBUI::Pane\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual void \fBsetItem\fP (\fBAWE::MediaItem\fP *item)"
.br
.RI "\fISet the item to display images for\&. \fP"
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBfanartChanged\fP (QPixmap image)"
.br
.RI "\fISent when the fanart image is changed\&. \fP"
.ti -1c
.RI "void \fBiconChanged\fP (QPixmap image)"
.br
.RI "\fISent when the icon image is changed\&. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImagePane\fP (QWidget *parent)"
.br
.RI "\fIMake with the given parent\&. \fP"
.ti -1c
.RI "\fB~ImagePane\fP ()"
.br
.RI "\fIDestroys this object\&. \fP"
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBrespondToIconChange\fP (\fBItemWidget\fP *icon)"
.br
.RI "\fIInternal slot for handling icon image changes\&. \fP"
.ti -1c
.RI "void \fBrespondToFanartChange\fP (\fBItemWidget\fP *fanart)"
.br
.RI "\fIInternal slot for handling fanart image changes\&. \fP"
.ti -1c
.RI "void \fBrespondToTempIconChange\fP (\fBItemWidget\fP *icon)"
.br
.RI "\fIInternal slot for handling temp icon image changes\&. \fP"
.ti -1c
.RI "void \fBrespondToTempFanartChange\fP (\fBItemWidget\fP *fanart)"
.br
.RI "\fIInternal slot for handling temp fanart image changes\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBAWE::MediaItem\fP * \fBmyMediaItem\fP"
.br
.RI "\fIThe item to display images for\&. \fP"
.ti -1c
.RI "QVBoxLayout * \fBmyMainLayout\fP"
.br
.RI "\fIThe main layout of this widget\&. \fP"
.ti -1c
.RI "\fBImageItemWidget\fP * \fBmyCurrentIcon\fP"
.br
.RI "\fIThe icon image displayed\&. \fP"
.ti -1c
.RI "\fBItemListWidget\fP * \fBmyIconList\fP"
.br
.RI "\fIThe list of icon images the user can choose from\&. \fP"
.ti -1c
.RI "\fBImageItemWidget\fP * \fBmyCurrentFanart\fP"
.br
.RI "\fIThe fanart image displayed\&. \fP"
.ti -1c
.RI "\fBItemListWidget\fP * \fBmyFanartList\fP"
.br
.RI "\fIThe list of fanart images the user can choose from\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Defines a class that holds icons and fanart images\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImagePane::ImagePane (QWidget *parent)"

.PP
Make with the given parent\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP The parent widget\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void UI::ImagePane::fanartChanged (QPixmapimage)\fC [signal]\fP"

.PP
Sent when the fanart image is changed\&. 
.PP
\fBParameters:\fP
.RS 4
\fIimage\fP The new fanart image\&. 
.RE
.PP

.SS "void UI::ImagePane::iconChanged (QPixmapimage)\fC [signal]\fP"

.PP
Sent when the icon image is changed\&. 
.PP
\fBParameters:\fP
.RS 4
\fIimage\fP The new icon image\&. 
.RE
.PP

.SS "void ImagePane::respondToFanartChange (\fBItemWidget\fP *fanart)\fC [private]\fP, \fC [slot]\fP"

.PP
Internal slot for handling fanart image changes\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfanart\fP The image item selected\&. 
.RE
.PP

.SS "void ImagePane::respondToIconChange (\fBItemWidget\fP *icon)\fC [private]\fP, \fC [slot]\fP"

.PP
Internal slot for handling icon image changes\&. 
.PP
\fBParameters:\fP
.RS 4
\fIicon\fP The image item selected\&. 
.RE
.PP

.SS "void ImagePane::respondToTempFanartChange (\fBItemWidget\fP *fanart)\fC [private]\fP, \fC [slot]\fP"

.PP
Internal slot for handling temp fanart image changes\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfanart\fP The image item highlighted\&. 
.RE
.PP

.SS "void ImagePane::respondToTempIconChange (\fBItemWidget\fP *icon)\fC [private]\fP, \fC [slot]\fP"

.PP
Internal slot for handling temp icon image changes\&. 
.PP
\fBParameters:\fP
.RS 4
\fIicon\fP The image item highlighted\&. 
.RE
.PP

.SS "void ImagePane::setItem (\fBAWE::MediaItem\fP *item)\fC [virtual]\fP, \fC [slot]\fP"

.PP
Set the item to display images for\&. 
.PP
\fBParameters:\fP
.RS 4
\fIitem\fP The item to display images for\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AWE Media Center from the source code\&.
