.TH "UI::MainWindow" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI::MainWindow \- 
.PP
The main window of AWEMC, which allows the user to browse through the application\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MainWindow\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "virtual void \fBsetContents\fP (\fBWindowContents\fP *contents)"
.br
.RI "\fIGet the settings browser object\&. \fP"
.ti -1c
.RI "virtual void \fBswitchToFolderBrowser\fP ()"
.br
.RI "\fISwitch to the folder browser\&. \fP"
.ti -1c
.RI "virtual void \fBopenFile\fP (\fBAWE::MediaFile\fP *file, \fBAWE::MediaPlayer\fP *player)"
.br
.RI "\fISwitch to the settings browser\&. \fP"
.ti -1c
.RI "virtual void \fBopenService\fP (\fBAWE::MediaService\fP *service)"
.br
.RI "\fIOpen the given media service\&. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent)"
.br
.RI "\fIConstruct the main window using AWEMC's global settings\&. \fP"
.ti -1c
.RI "virtual \fB~MainWindow\fP ()"
.br
.RI "\fIDestroys this object\&. \fP"
.ti -1c
.RI "virtual void \fBopen\fP ()"
.br
.RI "\fIShows this item in fullscreen and opens the contents\&. \fP"
.ti -1c
.RI "virtual \fBWindowContents\fP * \fBgetContents\fP ()"
.br
.RI "\fIGet the contents of the window\&. \fP"
.ti -1c
.RI "virtual \fBFolderBrowser\fP * \fBgetFolderBrowser\fP ()"
.br
.RI "\fIGet the folder browser object\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBFolderBrowser\fP * \fBmyFolderBrowser\fP"
.br
.RI "\fIThe folder browser pane\&. \fP"
.ti -1c
.RI "\fBWindowContents\fP * \fBmyCurrentContents\fP"
.br
.RI "\fIThe settings browser pane\&. \fP"
.ti -1c
.RI "QVBoxLayout * \fBmyLayout\fP"
.br
.RI "\fIThe layout for this window\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The main window of AWEMC, which allows the user to browse through the application\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (QWidget *parent)"

.PP
Construct the main window using AWEMC's global settings\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP The parent widget (usually nullptr)\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBWindowContents\fP * MainWindow::getContents ()\fC [virtual]\fP"

.PP
Get the contents of the window\&. 
.PP
\fBReturns:\fP
.RS 4
The contents of the window\&. 
.RE
.PP

.SS "\fBFolderBrowser\fP * MainWindow::getFolderBrowser ()\fC [virtual]\fP"

.PP
Get the folder browser object\&. 
.PP
\fBReturns:\fP
.RS 4
The folder browser object\&. 
.RE
.PP

.SS "void MainWindow::openFile (\fBAWE::MediaFile\fP *file, \fBAWE::MediaPlayer\fP *player)\fC [virtual]\fP, \fC [slot]\fP"

.PP
Switch to the settings browser\&. This is a convenience function, equivalent to \fCsetContents(getSettingsBrowser())\fP\&. Open the media file with the given player\&.
.PP
\fBParameters:\fP
.RS 4
\fIfile\fP The media file to play\&. 
.br
\fIplayer\fP The media player to use\&. 
.RE
.PP

.SS "void MainWindow::openService (\fBAWE::MediaService\fP *service)\fC [virtual]\fP, \fC [slot]\fP"

.PP
Open the given media service\&. 
.PP
\fBParameters:\fP
.RS 4
\fIservice\fP The service to open\&. 
.RE
.PP

.SS "void MainWindow::setContents (\fBWindowContents\fP *contents)\fC [virtual]\fP, \fC [slot]\fP"

.PP
Get the settings browser object\&. 
.PP
\fBReturns:\fP
.RS 4
The settings browser object\&. Set the contents of the window\&.
.RE
.PP
\fBParameters:\fP
.RS 4
\fIcontents\fP The new contents of the window\&. 
.RE
.PP

.SS "void MainWindow::switchToFolderBrowser ()\fC [virtual]\fP, \fC [slot]\fP"

.PP
Switch to the folder browser\&. This is a convenience function, equivalent to \fCsetContents(getFolderBrowser())\fP\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBWindowContents\fP* UI::MainWindow::myCurrentContents\fC [private]\fP"

.PP
The settings browser pane\&. The current contents pane\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AWE Media Center from the source code\&.
