.TH "UI::WindowContents" 3 "Sat May 10 2014" "Version 0.1" "AWE Media Center" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI::WindowContents \- 
.PP
An interface that describes what could be the contents of the main window\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WindowContents\&.h>\fP
.PP
Inherited by \fBUI::FolderBrowser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual QString \fBgetType\fP ()=0"
.br
.RI "\fIDescribes the type of contents\&. \fP"
.ti -1c
.RI "virtual void \fBsetParent\fP (\fBMainWindow\fP *window)=0"
.br
.RI "\fISet the parent of this contents pane (i\&.e\&., the main window)\&. \fP"
.ti -1c
.RI "virtual QWidget * \fBgetWidget\fP ()=0"
.br
.RI "\fIGets the main widget for this screen\&. \fP"
.ti -1c
.RI "virtual void \fBopen\fP ()=0"
.br
.RI "\fICalled after the widget is added to the window for additional setup\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An interface that describes what could be the contents of the main window\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual QString UI::WindowContents::getType ()\fC [pure virtual]\fP"

.PP
Describes the type of contents\&. For a \fCFileBrowser\fP, for example, this would return \fC'File Browser'\fP\&.
.PP
\fBReturns:\fP
.RS 4
A string describing the contents\&. 
.RE
.PP

.PP
Implemented in \fBUI::FolderBrowser\fP\&.
.SS "virtual QWidget* UI::WindowContents::getWidget ()\fC [pure virtual]\fP"

.PP
Gets the main widget for this screen\&. All of the \fBUI\fP elements for this window pane should be contained inside this widget (usually, this widget has a designated layout)\&.
.PP
\fBReturns:\fP
.RS 4
The main widget for this contents pane\&. 
.RE
.PP

.PP
Implemented in \fBUI::FolderBrowser\fP\&.
.SS "virtual void UI::WindowContents::setParent (\fBMainWindow\fP *window)\fC [pure virtual]\fP"

.PP
Set the parent of this contents pane (i\&.e\&., the main window)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwindow\fP The \fC\fBMainWindow\fP\fP of AWEMC\&. 
.RE
.PP

.PP
Implemented in \fBUI::FolderBrowser\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AWE Media Center from the source code\&.
